### ISSUE TITLE
ensure_writable limits the applicability of this awesome script and should be removed

### ISSUE THREAD

**Issue by btittelbach** [xolox/python-rotate-backups#18]
First, let me thank you for creating this nice script, which does exactly what I was looking for and so saved me from having to write something less fancy myself.

However, in order to make it work the way I needed it, I had to remove the `ensure_writable()` check.

I'm proposing that you might consider removing this check altogether and instead display a meaningful error message when the delete command actually fails and not before.
This script is, after all, intended for admins who should know what they are doing.
The check fails under certain conditions when the actual removal command would have performed perfectly fine.

In my case it wanted to give a `--removal-command` like e.g. `sudo rm <very specific directorytree>` or e.g. `sudo zfs destroy <only certain sapshots>` and NOT run the script using sudo or give the `--use-sudo` option, causing `test` or `find` to run as root, as there is no need for that. (It is good practice to limit sudo to one very specific command for that specific user running `rotate-backups`.)

This all would have worked perfectly out of the box (it does now), except for the overzealous `ensure_writable()` check at the beginning, which, though well intended, is actually not helpful and prohibits using the script in a safe manner.

**Comment by xolox** [comment]
Hey Bernhard and thanks for the feedback!

Your use case made me realize that `ensure_writable()` should be skipped when `--removal-command` is given because custom removal commands imply custom semantics (as your use case shows).

Furthermore this made me realize that these sanity checks can misjudge a situation in such a way that they prevent `rotate-backups` from being used, which is obviously bad. To this end I've added a new option `--force` that will make the program continue even if sanity checks failed.

Both of these changes are part of [rotate-backups 7.0](https://rotate-backups.readthedocs.io/en/latest/changelog.html#release-7-0-2020-02-12) which was just released. I hope and believe these changes adequately resolve your issue.

**Comment by btittelbach** [comment]
sound great :-)
Thanks!
