### ISSUE TITLE
Provide alternative datetime extraction strategies

### ISSUE THREAD

**Issue by aslafy-z** [xolox/python-rotate-backups#19]
Hi,

I'm trying to rotate some files but I have some trouble given that  the file names includes more digits than the date.

`sxx-01-00.1.1build133003_2019-07-23_04:00:01.zip` gets parsed to `datetime(1330, 3, 20, 19, 7, 23)`

I'm unable to save the files with other names since I don't manage the backups themselfs.
Is there a way I could give some insight to the script to understand my filenames?

It would be great if we could use a switch that use ctime or mtime instead of fuzzy matching the filename. Another way would be giving the user a way to specify a custom regexp to parse the file.
I thought of another way also, adding a custom 'wildcard' in the include pattern that says, match the date from that part of the file, eg: `sxx-*_%datetime%.zip`. It could also search for a date only where there is a wildcard char.

Thanks for building this awesome module, I used it in several other projects and it always worked as intended.

Best,

**Comment by rdiez** [comment]
I recently came across this question:

What is your favorite date and time format in a file name? [closed]
https://stackoverflow.com/questions/1248747/what-is-your-favorite-date-and-time-format-in-a-file-name

The format suggested for best readability was:

My-File--2009-12-31--23-59-59.txt

However, I cannot use that format because rotate-backup's timestamp regular expression is fixed, and it does not properly accept the "--" separator between date and time.

**Comment by statalex** [comment]
Hello,

I have implemented a timestamp option, so user will be totally responsible for the pattern, i also kept the TIMESTAMP as default pattern.

I haven't use the github before, so i dont know how to upload it. Could you help me?

**Comment by aslafy-z** [comment]
I suggest you have a look to https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github. Let us know if you need further help!

**Comment by xolox** [comment]
Hi all and thanks for the feedback! I just merged #23 and released [rotate-backups 7.2](https://rotate-backups.readthedocs.io/en/latest/changelog.html#release-7-2-2020-02-14).
